name: sonar
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  CONTAINER_REGISTRY: docker.io
  CONTAINER_IMAGE: samplerak
  IMAGE_TAG: ${{ github.run_number }}
  SONAR_HOST_URL: 'https://sonarcloud.io'
  REPOSITORY_NAME: sharon111edapal
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Login to Git Hub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.REPOSITORY_NAME }}
          password: ${{ secrets.RAK }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_NAME }}/${{ env.CONTAINER_IMAGE }}:${{ env.IMAGE_TAG }}    
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RAK }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.RAKSONAR }}
          
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.RAKSONAR }}
         SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
